meta_product_name: "WePublic"

meta_title: "WePublic · La plateforme participative"

meta_description: "WePublic est une plateforme de participation citoyenne qui vous permet de créer plus de vie au sein de votre commune"

meta_image: "logo.png"
